### ISSUE TITLE
ant design vue pro 原生cesium 使用这个组件，加载不了，一直报cesium

### ISSUE THREAD

**Issue by apgk** [dvgis/cesium-map#16]
1.项目先引入 原生 cesium 1.89.0版本
2.再次引入 cesium-map
3.项目采用局部注册
4.代码大概如下
`
import * as Cesium from 'cesium/Cesium'
import 'cesium/Widgets/widgets.css'
require('@dvgis/cesium-map')
 `
报 Cesium is not defined

**Comment by yu44303** [comment]
> 



> 

同样的问题你 你解决了么

**Comment by yu44303** [comment]
> 1.项目先引入 原生 cesium 1.89.0版本 2.再次引入 cesium-map 3.项目采用局部注册 4.代码大概如下 `import * as Cesium from 'cesium/Cesium' import 'cesium/Widgets/widgets.css' require('@dvgis/cesium-map')` 报 Cesium is not defined

同样的问题 你解决了么

**Comment by apgk** [comment]
> > 1. 项目先引入铯 1.89.0 2. 引入铯-map 3. 项目采用以下版本报告 4. 代码概略如下`import * as Cesium from 'cesium/Cesium' import 'cesium/Widgets/widgets.css' require('@dvgis/cesium-map')`： 铯未定义
> 
> 你的问题解决了么么哒
两种解决方式
1. 
import * as Cesium from 'cesium/Cesium'
window.Cesium =Cesium
require('@dvgis/cesium-map')

2.下载代码，更改其中涉及到的cesium 引用
为import * as Cesium from 'cesium/Cesium'
注意保留作者信息
其余我就没想到怎么解决了

**Comment by cavencj** [comment]
global.Cesium =  require(''cesium/Cesium'')
