### ISSUE TITLE
cesium加载百度个性化地图

### ISSUE THREAD

**Issue by z123-piad** [dvgis/cesium-map#28]
想要使用百度地图的个性化地图 但是网络上没有找到合适的解决方案

**Comment by cavencj** [comment]
现在个性化地图好像不能用了，应该是百度不开放了

**Comment by z123-piad** [comment]
(https://lbsyun.baidu.com/custom/index.htm)这个应该是旧版的百度个性化地图，页面初始化的时候有一个请求（https://api.map.baidu.com/getscript?v=2.0&ak=8d6c8b8f3749aed6b1aff3aad6f40e37&services=&t=20230321100542）返回的是一个js文件，后续的请求都和这个js文件有关。不知道能不能通过这个获取到切片呢？

**Comment by cavencj** [comment]
没有试过，这个js应该是baidu的sdk吧，
