### ISSUE TITLE
添加国内地图偏移问题

### ISSUE THREAD

**Issue by lxydft** [dvgis/cesium-map#8]
我用咱们的方法加载了百度的底图，然后添加了4326的shp创建的3dtiles，他们两个是有偏移，包括这个地址http://map.geoq.cn/arcgis/rest/services/ChinaOnlineStreetPurplishBlue/MapServer
的底图也是同样的情况。不知道这个问题咱们有解决方法没。

**Comment by cavencj** [comment]
已支持
